### ISSUE TITLE
COVID-19 graph/data stale since May 28th?

### ISSUE THREAD

**Issue by JulienMoisan** [epiforecasts/jekyll-epiforecasts-website#3]
Hello!

First thanks very much for all the hard work in making this extremely useful information available to the broader community.

I noticed that the website's data seems to not have updated in the past weeks, with graphs seemingly stopping on June 8th (possibly corresponding to nowcasts going until 28th of May as the website indicates?). Is this expected — are you guys no longer updating this data as frequently?

Thank you,
All the best,
Julien

**Comment by seabbs** [comment]
Hi Julien, 

Sorry only just seen this. See our latest estimates here: https://github.com/epiforecasts/covid-rt-estimates

Will be updated on the website shortly.
