### ISSUE TITLE
Link to packages

### ISSUE THREAD

**Issue by seabbs** [epiforecasts/jekyll-epiforecasts-website#5]
Hi, 

It would be great if we could link out to some of our dev packages - so people have a central place to see our work. Not totally sure how to make changes to the website but happy to do so if given a few pointers :smile:

**Comment by sbfnk** [comment]
Had a go at this - please feel free to amend in https://github.com/epiforecasts/epiforecasts.github.io/blob/master/software.md

**Comment by seabbs** [comment]
Typo fixed in #10. Looks good to me otherwise 🥳
